enum MenuState {MAIN, HOME, JOG, PAN, TRUCK, PARALLAX, VALUE_ENTRY} current_state;
enum ButtonAction {NAVIGATE, UPDATE_VALUE, MODIFY_INPUT};
enum DisplayType {CIRCLE, RECTANGLE, TRIANGLE, ARROW};
enum TriangleDirection{NERP, EAMST, SORTH, WIBBLES};
enum Unit {INCH, CENTIMETER, SECOND, MINUTE};