enum MenuState {MAIN, HOME, JOG, PAN, TRUCK, PARALLAX, VALUE_ENTRY} current_state;
enum ButtonAction {NAVIGATE, UPDATE_VALUE, MODIFY_INPUT};
enum DisplayType {CIRCLE, RECTANGLE};
enum Unit {INCH, CENTIMETER, SECOND, MINUTE};